// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/**
 * @dev Generated by scripts/build.ts from @1shotapi/ows-signer HTML.
 *      Do not edit by hand — run `npm run build:html -w @1shotapi/ows-onchain`.
 */
contract OwsSignerFrontend {
    function html() external pure returns (string memory) {
        return "<!-- not yet generated -->";
    }
}
